---
abstract: 'Write a test that reports used module versions'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101582, CPAN::Meta::Converter version 2.101591'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-ReportVersions
provides:
  Dist::Zilla::Plugin::ReportVersions:
    file: lib/Dist/Zilla/Plugin/ReportVersions.pm
    version: 1.101600
requires:
  Dist::Zilla::Plugin::InlineFiles: 0
  Moose: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-ReportVersions
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-ReportVersions/
  repository: http://github.com/hanekomu/Dist-Zilla-Plugin-ReportVersions
version: 1.101600
